# Generated by Django 4.2.8 on 2023-12-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("M1", models.IntegerField()),
                ("M2", models.IntegerField()),
                ("M3", models.IntegerField()),
                ("M4", models.IntegerField()),
                ("q1_1", models.IntegerField()),
                ("q2_1", models.IntegerField()),
                ("q3_1", models.IntegerField()),
                ("q4_1", models.IntegerField()),
                ("q5_1", models.IntegerField()),
                ("q6_1", models.IntegerField()),
                ("q7_1", models.IntegerField()),
                ("q8_1", models.IntegerField()),
                ("q9_1", models.IntegerField()),
                ("q10_1", models.IntegerField()),
                ("q11_1", models.IntegerField()),
                ("q12_1", models.IntegerField()),
                ("q13_1", models.IntegerField()),
                ("q14_1", models.IntegerField()),
                ("q15_1", models.IntegerField()),
                ("q16_1", models.IntegerField()),
                ("q17_1", models.IntegerField()),
                ("q18_1", models.IntegerField()),
                ("q19_1", models.IntegerField()),
                ("q20_1", models.IntegerField()),
                ("q21_1", models.IntegerField()),
                ("q22_1", models.IntegerField()),
                ("q23_1", models.IntegerField()),
                ("q24_1", models.IntegerField()),
                ("q25_1", models.IntegerField()),
                ("q26_1", models.IntegerField()),
                ("q27_1", models.IntegerField()),
                ("q28_1", models.IntegerField()),
                ("q29_1", models.IntegerField()),
                ("q30_1", models.IntegerField()),
                ("q31_1", models.IntegerField()),
                ("q32_1", models.IntegerField()),
                ("q33_1", models.IntegerField()),
                ("q34_1", models.IntegerField()),
                ("q35_1", models.IntegerField()),
                ("q36_1", models.IntegerField()),
                ("q37_1", models.IntegerField()),
                ("q38_1", models.IntegerField()),
                ("q39_1", models.IntegerField()),
                ("q40_1", models.IntegerField()),
            ],
        ),
    ]
