# Generated by Django 4.2.8 on 2023-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0004_alter_robot_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
